package easysplit.model.enums;

public enum OperationType {

  IS_USER_EXIST, SIGN_UP, LOG_IN, CREATE_TEAM, IS_TEAM_EXIST, GET_TEAM_SET, GET_MEMBER_SET,
  ADD_EXPENSE, SHOW_HISTORY, SHOW_SNAPSHOT, MAKE_PAYMENT, CONFIRM_PAYMENT, SHOW_PAYMENT_HISTORY
}
